# files
layouts: ./_/layouts
destination: ./_/site
sass:
  sass_dir: ./_/sass

exclude:
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
  - _deprecated

# Markdown
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      category: "Others"

# Site info
url: https://cheatsheets.ciscodude.net
title: Cheatsheets

# Google analytics
#analytics:
#  hostname: ricostacruz.com
#  id: "UA-20473929-1"

category_names:
  - Apps
  - Cisco
  - CLI
  - Code
  - Devops
  - Git
  - Markup
  - SaltStack
  - Vim
  - WebDev
  - Others
